### ISSUE TITLE
Unintuitive border width configuration

### ISSUE THREAD

**Issue by gikari** [nclarius/Plasma-window-decorations#1]
I installed the extension from the KDE Store, and got very thick borders:
![Screenshot_20220105_174659](https://user-images.githubusercontent.com/14205339/148236975-0a26953a-e7a7-49cf-a929-3ead9fb04f7f.png)

Then I tried to change them via Window border size option in the window decoration settings:
![Screenshot_20220105_183317](https://user-images.githubusercontent.com/14205339/148244362-7720d23f-3722-4eed-9540-f1a4461076f2.png)

But as you can see, it has no effect. However, it should.

I discovered, that the window borders could be changed via config file, however, while I think, that fine-tuning is nice, initially, I think it creates confusion.

## Additional Info

Additionally, I tried to change the border width via config file, but is failed to apply the changes correctly:
![Screenshot_20220105_183641](https://user-images.githubusercontent.com/14205339/148244959-9460f036-1622-4dca-a53d-de3b3b2f4d9e.png)

I do not believe, that this is 1 point width :)

Also, there are settings, like padding and from the default config I see, that they are set to some magical numbers. I tried to change them, and it somehow moves the colored border around windows:
![Screenshot_20220105_184201](https://user-images.githubusercontent.com/14205339/148245857-b5ca2811-540d-407e-9b3f-73f9d2faba09.png)

## Configuration Info

I use 125% display scaling on X11 session.

**Comment by nclarius** [comment]
So did I understand it correctly that changing the border width via the GUI did not have the desired effect, but doing it in the config file did? And that the only problem remaining is the border at the top?  

For the top border, use `TitleEdgeTop` and `TitleEdgeTopMaximized`.

As for why the borders came out too thick, I imagine this might be due to the scaling.

If you find the config file unintuitive - sorry, that's just how KDE's Aurorae theming system works, nothing I can do about that.

**Comment by gikari** [comment]
> So did I understand it correctly that changing the border width via the GUI did not have the desired effect, but doing it in the config file did? And that the only problem remaining is the border at the top?

Yes, but changing the config file is not simple, as just changing 4 key-value pairs (according to the docs). I changed the BorderTop/Right/Left/Bottom, but nothing changed, when I reapplied the decoration.

Something changed, but in a mostly unpredictable way, when I touched the `Padding` key-value pairs and the `EdgeTop` ones you mentioned.

I think it would be useful to have some docs on what each key-value pair does and how to change them to have a border with width of X pixels (also the fact, that these values are affected by scaling should be stated as well).

**Comment by nclarius** [comment]
> Yes, but changing the config file is not simple, as just changing 4 key-value pairs (according to the docs). I changed the BorderTop/Right/Left/Bottom, but nothing changed, when I reapplied the decoration.

I'm still not sure I understand. Some change in the config file did the trick, but it wasn't the four `Border`/`Edge` values?

> Something changed, but in a mostly unpredictable way, when I touched the Padding key-value pairs and the EdgeTop ones you mentioned.

If you mess around with code that you don't understand what does, unwanted things happening is what is to be expected :)

> I think it would be useful to have some docs on what each key-value pair does and how to change them to have a border with width of X pixels (also the fact, that these values are affected by scaling should be stated as well).

Here: https://techbase.kde.org/User:Mgraesslin/Aurorae

To clarify: I'm not the one who designed that config file. That's the format required by the Aurorae theming engine, the theme designers just fill in the values. Referring you to the official docs is all I can do. If you find the way Aurorae configuration works unsatisfactory, that's something you should address with the developers of the KDE theming system.

**Comment by gikari** [comment]
> I'm still not sure I understand. Some change in the config file did the trick, but it wasn't the four `Border`/`Edge` values?

Yes. I changed the `BorderX` values, as the README recommended, but it didn't help.

I see, you changed the README, with the link to the docs. That's what I wanted to propose, so thank you.
