### ISSUE TITLE
Border Radius

### ISSUE THREAD

**Issue by RandomLegend** [nclarius/Plasma-window-decorations#3]
Hello there!

Is there any way to configure a border/frame radius?

I use Picom (but used KWin-Compositor in the past with some rounded-corners scripts) and whenever i use rounded corners with frames (like yours, but also on breeze or bismuth) i get this:

![image](https://user-images.githubusercontent.com/38812603/185210564-0d8b6eea-de08-4a19-bc5f-4c1eee43a0da.png)

The current border radius of Picom is set to 15. Is it possible to also get a radius on this frame so it doesn't get "cut in" like that?

Thanks in advance!

**Comment by nclarius** [comment]
No, this is unfortunately not configurable, and not possible to make configurable. Aurorae decorations are just a bunch of SVGs. You could edit it in a vector graphics editor such as Inkscape yourself.  The relevant file is `~/.local/share/aurorae/themes/ActiveAccentFrame/decoration.svg`.

**Comment by RandomLegend** [comment]
Thanks for the hint...yeah i have absolutely no idea on how to properly edit this to a 15px radius. But i'll make a backup and try :-D 

Thanks very much!
