### ISSUE TITLE
[Feature Request] Rounding Config

### ISSUE THREAD

**Issue by CentillionJinx** [nclarius/Plasma-window-decorations#6]
Rainbow border (animated), just like the following image, from hyprland:

![image](https://github.com/nclarius/Plasma-window-decorations/assets/73017980/ce3913ff-45f7-426e-b76d-1e435ca0832f)

Just a thought...

**Comment by nclarius** [comment]
That looks cool but is unfortunately not possible to implement with the KDE framework that this extension is using, so I'm going to have to close this request as not planned.

**Comment by CentillionJinx** [comment]
Hmm, how about rounding the corners of the current window decoration? a bit cliche, but could use a config file to adjust if needed.

**Comment by nclarius** [comment]
Making that configurable is not possible either, the border radius is fixed by what is drawn in decoration.svg. If you know a little about how editing SVGs works, you could give it a shot at changing it yourself to your own liking.

**Comment by CentillionJinx** [comment]
Aight!! Thanks for the updates and follow ups
